
title: RCHD
description: "Red Colombiana de Humanidades Digitales"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rchd.com.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ReHDi_Co
facebook_username: redcolhd
github_username: rchd-repo
github_repo:  # the GitHub repo name for your project

# Build settings
remote_theme: broccolini/swiss